# Generated by Django 4.0.5 on 2023-10-05 06:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.CharField(max_length=50, verbose_name='Company')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('self_employed', 'Self-employed'), ('freelance', 'Freelance'), ('contract', 'Contract'), ('internship', 'Internship'), ('apprenticeship', 'Apprenticeship'), ('leadership_program', 'Leadership Program'), ('indirect_contract', 'Indirect Contract'), ('volunteer', 'Volunteer'), ('other', 'Other')], max_length=50, null=True, verbose_name='Employment Type')),
                ('about', models.CharField(blank=True, max_length=125, null=True, verbose_name='About')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('is_current', models.BooleanField(default=False, verbose_name='Is Current')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='profiles.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='RoleSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Order')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_skills', to='roles.role', verbose_name='Role')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_skills', to='skills.skill', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Role Skill',
                'verbose_name_plural': 'Role Skills',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='role', through='roles.RoleSkill', to='skills.skill', verbose_name='Skills'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('description', models.CharField(max_length=125, verbose_name='Description')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Order')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='roles.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['order'],
            },
        ),
    ]
