# Generated by Django 4.0.5 on 2023-06-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('self_employed', 'Self-employed'), ('freelance', 'Freelance'), ('contract', 'Contract'), ('internship', 'Internship'), ('apprenticeship', 'Apprenticeship'), ('leadership_program', 'Leadership Program'), ('indirect_contract', 'Indirect Contract'), ('volunteer', 'Volunteer'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
