# Generated by Django 4.0.5 on 2023-10-05 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('language', models.CharField(max_length=50, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ('name',),
                'unique_together': {('name', 'language')},
            },
        ),
    ]
