# Generated by Django 4.0.5 on 2023-10-04 05:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('school_name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='profiles.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EducationSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_skills', to='education.education', verbose_name='Education')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_skills', to='skills.skill', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Education Skill',
                'verbose_name_plural': 'Education Skills',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='education',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='education', through='education.EducationSkill', to='skills.skill'),
        ),
    ]
