# Generated by Django 4.0.5 on 2023-10-05 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        ('profiles', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='profiles.profile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='educationskill',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_skills', to='education.education', verbose_name='Education'),
        ),
        migrations.AddField(
            model_name='educationskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_skills', to='skills.skill', verbose_name='Skill'),
        ),
        migrations.AddField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='profiles.profile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='education',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='education', through='education.EducationSkill', to='skills.skill', verbose_name='Skills'),
        ),
    ]
