# Generated by Django 4.0.5 on 2023-10-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_education_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
