# Generated by Django 4.0.5 on 2023-10-05 03:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_skills'),
        ('education', '0004_alter_education_gpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('level', models.CharField(choices=[('basic', 'Elementary proficiency'), ('intermediate', 'Limited working proficiency'), ('advanced', 'Professional working proficiency'), ('fluent', 'Full professional proficiency'), ('native', 'Native or bilingual proficiency')], max_length=12, verbose_name='Level')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='profiles.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
            },
        ),
    ]
